# Worker Configuration
worker:
  concurrency: 4
  retry:
    max_retries: 3
    retry_delay: 60
  monitoring:
    enable: true

# Task Queue Configuration
task_queue:
  sqlite:
    path: "~/.local/share/paise2/tasks.db"
    immediate: false  # Set to true for development debugging
  redis:
    host: "localhost"
    port: 6379
    db: 0
